name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run : echo "${{ steps.greet.outputs.time }}"
        ##hello
