name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        uses: AjayprasanthRajagopal/github-actions-test@master

        ##hello
