name: ShellCommands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: echo  user name
        run: echo "Hello Ajayprasanth"
      - name: Version Check
        run: |
          npm protractor -version
          git --version

