on: pull_request
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: $GITHUB_REPOSITORY 
          SLACK_TITLE: 'Slack Notification Demo'
          SLACK_USERNAME : 'Ajayprasanth R'
          SLACK_COLOR: 'Green'
          ##